### PR TITLE
remove v2 loggregator ingestion option for log-cache

### PR DESCRIPTION
**Pull request by Benjamintf1**
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Testing performed?

- [ ] Unit tests
- [ ] Integration tests
- [ ] Acceptance tests

## Checklist:

- [x] This PR is being made against the `main` branch, or relevant version branch
- [ ] I have made corresponding changes to the documentation
- [ ] I have added testing for my changes

If you have any questions, or want to get attention for a PR or issue please reach out on the [#logging-and-metrics channel in the cloudfoundry slack](https://cloudfoundry.slack.com/archives/CUW93AF3M)

### CODE REVIEW

**Review by ctlong — APPROVED** [review]

**Comment by ctlong** [comment]
The ops files [use-log-cache-nozzle-windows2019.yml](https://github.com/cloudfoundry/cf-deployment/blob/develop/operations/use-log-cache-nozzle-windows2019.yml) & [use-log-cache-nozzle.yml](https://github.com/cloudfoundry/cf-deployment/blob/develop/operations/use-log-cache-nozzle.yml) in cf-d need to be deprecated as described [here](https://github.com/cloudfoundry/cf-deployment/blob/main/ops-file-promotion-workflow.md) before it can be merged.

**Comment by ctlong** [comment]
There might also be a lot of documentation in this repo to change - I haven't looked into it.

**Comment by chombium** [comment]
Nice cleanup @Benjamintf1

**Review by ctlong — APPROVED** [review]

**Comment by ctlong** [comment]
https://github.com/cloudfoundry/docs-loggregator/pull/70

**Pull request merged**
